### ISSUE TITLE
Run the model with our own data

### ISSUE THREAD

**Issue by sofiagermer** [CallMeL/Empathetic-Dialogue-System#25]
## TODOs
- [x] Run the model with our own data
- [x] visualize the training process results
- [x] Doing research for other available models and tryout: LSTM
